# Generated by Django 5.0.3 on 2024-05-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpekerjaan',
            name='nama',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
