# Generated by Django 5.0.3 on 2024-05-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_subpekerjaan_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='pekerjaan',
            name='tipe_pekerjaan',
            field=models.CharField(choices=[('Konstruksi', 'Konstruksi'), ('Pra Konstruksi', 'Pra Konstruksi')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pekerjaan',
            name='harga_total_pekerjaan',
            field=models.DecimalField(decimal_places=0, default=0.0, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='subpekerjaan',
            name='harga_satuan',
            field=models.DecimalField(decimal_places=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='subpekerjaan',
            name='harga_total',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='subpekerjaan',
            name='kuantiti',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proyek', models.CharField(max_length=255)),
                ('pekerjaan_konstruksi', models.ManyToManyField(limit_choices_to={'tipe_pekerjaan': 'Konstruksi'}, related_name='konstruksi_proyek', to='myapp.pekerjaan')),
                ('pekerjaan_pra_konstruksi', models.ManyToManyField(limit_choices_to={'tipe_pekerjaan': 'Pra Konstruksi'}, related_name='pra_konstruksi_proyek', to='myapp.pekerjaan')),
            ],
        ),
    ]
