# Generated by Django 5.0.3 on 2024-05-22 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pekerjaan_tipe_pekerjaan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_referensi', models.CharField(max_length=255)),
                ('harga_satuan', models.DecimalField(decimal_places=0, max_digits=18)),
            ],
        ),
        migrations.AddField(
            model_name='subpekerjaan',
            name='referensi_harga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.referensi'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
