# Generated by Django 5.0.3 on 2024-06-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_pdfhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfhash',
            name='file_name',
            field=models.CharField(default='aa', max_length=255),
        ),
    ]
